/**
 * PQ API v2Lib
 *
 * This file was automatically generated for PayQuicker by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DocumentTypes
 */
export enum DocumentTypes {
  UNDEFINED = 'UNDEFINED',
  ARMEDFORCESIDCARD = 'ARMED_FORCES_ID_CARD',
  BANKORCREDITCARDSTATEMENT = 'BANK_OR_CREDIT_CARD_STATEMENT',
  BANKREFERENCELETTER = 'BANK_REFERENCE_LETTER',
  BIRTHCERTIFICATE = 'BIRTH_CERTIFICATE',
  DEEDPOLL = 'DEED_POLL',
  DEEDPOLLNAMECHANGE = 'DEED_POLL_NAME_CHANGE',
  DRIVERSLICENSE = 'DRIVERS_LICENSE',
  DRIVERSLICENSEBACK = 'DRIVERS_LICENSE_BACK',
  DRIVERSLICENSENAMECHANGE = 'DRIVERS_LICENSE_NAME_CHANGE',
  FIREARMSLICENSE = 'FIREARMS_LICENSE',
  HEALTHIDCARD = 'HEALTH_ID_CARD',
  HIGHQUALITYHEADSHOT = 'HIGH_QUALITY_HEADSHOT',
  MARRIAGELICENSE = 'MARRIAGE_LICENSE',
  MARRIAGELICENSENAMECHANGE = 'MARRIAGE_LICENSE_NAME_CHANGE',
  MATRICULACONSULARIDCARD = 'MATRICULA_CONSULAR_ID_CARD',
  NATIONALIDENTITYCARD = 'NATIONAL_IDENTITY_CARD',
  NATIONALIDENTITYCARDFRONT = 'NATIONAL_IDENTITY_CARD_FRONT',
  NATIONALIDENTITYCARDBACK = 'NATIONAL_IDENTITY_CARD_BACK',
  NATIONALINSURANCECARD = 'NATIONAL_INSURANCE_CARD',
  OFFICIALNAMECHANGEDOCUMENT = 'OFFICIAL_NAME_CHANGE_DOCUMENT',
  OTHERGOVERNMENTISSUEDID = 'OTHER_GOVERNMENT_ISSUED_ID',
  PASSPORT = 'PASSPORT',
  PAYSTUB = 'PAY_STUB',
  PROOFOFAGECARD = 'PROOF_OF_AGE_CARD',
  PROVISIONALDRIVERSLICENSE = 'PROVISIONAL_DRIVERS_LICENSE',
  PUBLICSERVICECARDFRONT = 'PUBLIC_SERVICE_CARD_FRONT',
  PUBLICSERVICECARDBACK = 'PUBLIC_SERVICE_CARD_BACK',
  RESIDENTCARD = 'RESIDENT_CARD',
  RESIDENTIMMIGRATIONCARD = 'RESIDENT_IMMIGRATION_CARD',
  SOCIALSECURITYCARD = 'SOCIAL_SECURITY_CARD',
  TAXIDENTIFICATIONCARDORLETTER = 'TAX_IDENTIFICATION_CARD_OR_LETTER',
  TAXSTATEMENT = 'TAX_STATEMENT',
  UTILITYBILL = 'UTILITY_BILL',
  VOTERSCARD = 'VOTERS_CARD',
  ARMEDFORCESIDCARDBACK = 'ARMED_FORCES_ID_CARD_BACK',
  TAXDOCUMENT = 'TAX_DOCUMENT',
  HEALTHIDCARDBACK = 'HEALTH_ID_CARD_BACK',
  PROOFOFAGECARDBACK = 'PROOF_OF_AGE_CARD_BACK',
  INDEPENDENTPERSONALREFERENCEDOCUMENT = 'INDEPENDENT_PERSONAL_REFERENCE_DOCUMENT',
  VIDEOCALLFILE = 'VIDEO_CALL_FILE',
  HOMEORAUTOINSURANCECERTIFICATEORSCHEDULE = 'HOME_OR_AUTO_INSURANCE_CERTIFICATE_OR_SCHEDULE',
  DIVORCEDECREENAMECHANGE = 'DIVORCE_DECREE_NAME_CHANGE',
  CIVILPARTNERSHIPREGISTRATIONNAMECHANGE = 'CIVIL_PARTNERSHIP_REGISTRATION_NAME_CHANGE',
  RENTAGREEMENT = 'RENT_AGREEMENT',
  VEHICLEREGISTRATION = 'VEHICLE_REGISTRATION',
  BENEFITSCONFIRMATIONLETTER = 'BENEFITS_CONFIRMATION_LETTER',
  RESIDENTCARDBACK = 'RESIDENT_CARD_BACK',
  BANKORCREDITCARDSTATEMENT2 = 'BANK_OR_CREDIT_CARD_STATEMENT2',
  LOANACCOUNTSTATEMENT = 'LOAN_ACCOUNT_STATEMENT',
  PROCESSEDCHECK = 'PROCESSED_CHECK',
  RESIDENTIALDIRECTORYLISTING = 'RESIDENTIAL_DIRECTORY_LISTING',
  GENERICDOCUMENT = 'GENERIC_DOCUMENT',
  GOVERNMENTISSUEDPHOTOID = 'GOVERNMENT_ISSUED_PHOTOID',
  GOVERNMENTISSUEDPHOTOIDBACK = 'GOVERNMENT_ISSUED_PHOTO_ID_BACK',
  SOCIALINSURANCENUMBERCARD = 'SOCIAL_INSURANCE_NUMBER_CARD',
  SOCIALINSURANCENUMBERLETTER = 'SOCIAL_INSURANCE_NUMBER_LETTER',
  OTHERSOCIALINSURANCENUMBERDOCUMENT = 'OTHER_SOCIAL_INSURANCE_NUMBER_DOCUMENT',
  PLASTICCARDCUSTOMIMAGE = 'PLASTIC_CARD_CUSTOM_IMAGE',
}

/**
 * Schema for DocumentTypes
 */
export const documentTypesSchema: Schema<DocumentTypes> = stringEnum(DocumentTypes);
