/**
 * PQ API v2Lib
 *
 * This file was automatically generated for PayQuicker by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Fees
 */
export enum Fees {
  BANKTRANSFERREVERSALSTOPNOC = 'BANK_TRANSFER_REVERSAL_STOP_NOC',
  PAPERCHECKSTOP = 'PAPER_CHECK_STOP',
  INSTANTPAYMENT = 'INSTANT_PAYMENT',
  ACCOUNTDIRECTDEPOSIT = 'ACCOUNT_DIRECT_DEPOSIT',
  INBOUNDWIRE = 'INBOUND_WIRE',
  PLASTICCARDPURCHASEDECLINED = 'PLASTIC_CARD_PURCHASE_DECLINED',
  ATMDECLINED = 'ATM_DECLINED',
  CLEARNEGATIVEBALANCE = 'CLEAR_NEGATIVE_BALANCE',
  PLASTICCARDISSUANCE = 'PLASTIC_CARD_ISSUANCE',
  PLASTICCARDREPLACEMENTFRAUD = 'PLASTIC_CARD_REPLACEMENT_FRAUD',
  PLASTICCARDREPLACEMENTLOSTORSTOLEN = 'PLASTIC_CARD_REPLACEMENT_LOST_OR_STOLEN',
  PLASTICCARDREPLACEMENTEXPIRED = 'PLASTIC_CARD_REPLACEMENT_EXPIRED',
  BANKTRANSFERCURRENCYCONVERSION = 'BANK_TRANSFER_CURRENCY_CONVERSION',
  PAPERCHECKISSUANCECURRENCYCONVERSION = 'PAPER_CHECK_ISSUANCE_CURRENCY_CONVERSION',
  PLASTICCARDPINPURCHASE = 'PLASTIC_CARD_PIN_PURCHASE',
  FOREIGNEXCHANGECONVERSION = 'FOREIGN_EXCHANGE_CONVERSION',
  ATMCASHWITHDRAWALREMOTECURRENCYFOREIGNEXCHANGE = 'ATM_CASH_WITHDRAWAL_REMOTE_CURRENCY_FOREIGN_EXCHANGE',
  PAPERSTATEMENT = 'PAPER_STATEMENT',
  BANKTRANSFER = 'BANK_TRANSFER',
  PAPERCHECKISSUANCE = 'PAPER_CHECK_ISSUANCE',
  ACCOUNTENROLLMENT = 'ACCOUNT_ENROLLMENT',
  MONTHLYMAINTENANCEINACTIVEACCOUNT = 'MONTHLY_MAINTENANCE_INACTIVE_ACCOUNT',
  MONTHLYMAINTENANCEACTIVEACCOUNT = 'MONTHLY_MAINTENANCE_ACTIVE_ACCOUNT',
  ACCOUNTCLOSURE = 'ACCOUNT_CLOSURE',
  PLASTICCARDPURCHASEOUTSIDEUSA = 'PLASTIC_CARD_PURCHASE_OUTSIDE_USA',
  EXTERNALINITIATEDBANKTRANSFER = 'EXTERNAL_INITIATED_BANK_TRANSFER',
  COBRANDEDACCOUNTPROCESSINGORDERFEE = 'CO_BRANDED_ACCOUNT_PROCESSING_ORDER_FEE',
  ATMCASHWITHDRAWALFEELOCALCURRENCY = 'ATM_CASH_WITHDRAWAL_FEE_LOCAL_CURRENCY',
  ATMCASHWITHDRAWALFEEOUTSIDECURRENCY = 'ATM_CASH_WITHDRAWAL_FEE_OUTSIDE_CURRENCY',
  ATMBALANCEINQUIRYFEE = 'ATM_BALANCE_INQUIRY_FEE',
  BANKTELLERCASHWITHDRAWALFEE = 'BANK_TELLER_CASH_WITHDRAWAL_FEE',
  BANKTELLERCASHWITHDRAWALDECLINEFEE = 'BANK_TELLER_CASH_WITHDRAWAL_DECLINE_FEE',
  COMPANYBULKMONTHLYFEE = 'COMPANY_BULK_MONTHLY_FEE',
  PAYMENTESCHEATMENTFEE = 'PAYMENT_ESCHEATMENT_FEE',
  SPENDBACKPROCESSINGFEE = 'SPENDBACK_PROCESSING_FEE',
  VIRTUALPLASTICCARDREPLACEMENTFRAUD = 'VIRTUAL_PLASTIC_CARD_REPLACEMENT_FRAUD',
  VIRTUALPLASTICCARDREPLACEMENTLOSTORSTOLEN = 'VIRTUAL_PLASTIC_CARD_REPLACEMENT_LOST_OR_STOLEN',
  VIRTUALPLASTICCARDREPLACEMENTEXPIRED = 'VIRTUAL_PLASTIC_CARD_REPLACEMENT_EXPIRED',
  REVERSEFEE = 'REVERSE_FEE',
  LOADSERVICEFEE = 'LOAD_SERVICE_FEE',
  PAYMENTSUBSCRIPTIONFEE = 'PAYMENT_SUBSCRIPTION_FEE',
  AUTOACHFEE = 'AUTO_ACH_FEE',
  UNDEFINED = 'UNDEFINED',
  BULKMONTHLYFEE = 'BULK_MONTHLY_FEE',
  VIRTUALPLASTICCARDISSUANCE = 'VIRTUAL_PLASTIC_CARD_ISSUANCE',
}

/**
 * Schema for Fees
 */
export const feesSchema: Schema<Fees> = stringEnum(Fees);
