/**
 * PQ API v2Lib
 *
 * This file was automatically generated for PayQuicker by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PrepaidCardAuthorizations
 */
export enum PrepaidCardAuthorizations {
  UNDEFINED = 'UNDEFINED',
  BANKTRANSFER = 'BANK_TRANSFER',
  PAPERCHECK = 'PAPER_CHECK',
  DEPOSIT = 'DEPOSIT',
  CARDPURCHASE = 'CARD_PURCHASE',
  CARDPURCHASEREFUND = 'CARD_PURCHASE_REFUND',
  FEE = 'FEE',
  FEEREFUND = 'FEE_REFUND',
  PAYMENT = 'PAYMENT',
  CANCELLEDPAYMENT = 'CANCELLED_PAYMENT',
  CASHWITHDRAWAL = 'CASH_WITHDRAWAL',
  SPENDBACK = 'SPENDBACK',
  BANKTRANSFERREVERSAL = 'BANK_TRANSFER_REVERSAL',
  SPENDBACKRETURN = 'SPENDBACK_RETURN',
  BANKTRANSFERRETURN = 'BANK_TRANSFER_RETURN',
  PREPAIDCARDLOAD = 'PREPAID_CARD_LOAD',
  PREPAIDCARDUNLOAD = 'PREPAID_CARD_UNLOAD',
  PROVISIONALREFUND = 'PROVISIONAL_REFUND',
  PAYMENTRETRACTION = 'PAYMENT_RETRACTION',
  ACCOUNTTOACCOUNTTRANSFER = 'ACCOUNT_TO_ACCOUNT_TRANSFER',
  ESCHEATEDFUNDSRETURN = 'ESCHEATED_FUNDS_RETURN',
  UNSETTLEDAUTHORIZATION = 'UNSETTLED_AUTHORIZATION',
  FEEREBATE = 'FEE_REBATE',
  EFTFXMARGIN = 'EFT_FX_MARGIN',
}

/**
 * Schema for PrepaidCardAuthorizations
 */
export const prepaidCardAuthorizationsSchema: Schema<PrepaidCardAuthorizations> = stringEnum(PrepaidCardAuthorizations);
