/**
 * PQ API v2Lib
 *
 * This file was automatically generated for PayQuicker by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransferTypes
 */
export enum TransferTypes {
  ACCOUNTTOACCOUNTTRANSFER = 'ACCOUNT_TO_ACCOUNT_TRANSFER',
  BANKTRANSFER = 'BANK_TRANSFER',
  BANKTRANSFERRETURN = 'BANK_TRANSFER_RETURN',
  BANKTRANSFERREVERSAL = 'BANK_TRANSFER_REVERSAL',
  CANCELLEDPAYMENT = 'CANCELLED_PAYMENT',
  CARDPURCHASE = 'CARD_PURCHASE',
  CARDPURCHASEREFUND = 'CARD_PURCHASE_REFUND',
  CASHWITHDRAWAL = 'CASH_WITHDRAWAL',
  DEPOSIT = 'DEPOSIT',
  ESCHEATEDFUNDSRETURN = 'ESCHEATED_FUNDS_RETURN',
  FEE = 'FEE',
  FEEREFUND = 'FEE_REFUND',
  PAPERCHECK = 'PAPER_CHECK',
  PAYMENT = 'PAYMENT',
  PAYMENTRETRACTION = 'PAYMENT_RETRACTION',
  PREPAIDCARDLOAD = 'PREPAID_CARD_LOAD',
  PREPAIDCARDUNLOAD = 'PREPAID_CARD_UNLOAD',
  PROVISIONALREFUND = 'PROVISIONAL_REFUND',
  SPENDBACK = 'SPENDBACK',
  SPENDBACKRETURN = 'SPENDBACK_RETURN',
}

/**
 * Schema for TransferTypes
 */
export const transferTypesSchema: Schema<TransferTypes> = stringEnum(TransferTypes);
