/**
 * PQ API v2Lib
 *
 * This file was automatically generated for PayQuicker by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for WebhookNamespaces
 */
export enum WebhookNamespaces {
  BANKACCOUNTSCREATED = 'BANKACCOUNTS.CREATED',
  BANKACCOUNTSUPDATEDDETAILSMODIFIED = 'BANKACCOUNTS.UPDATED.DETAILS.MODIFIED',
  BANKACCOUNTSUPDATEDSTATUSAPPROVED = 'BANKACCOUNTS.UPDATED.STATUS.APPROVED',
  BANKACCOUNTSUPDATEDSTATUSCOMPLIANCEHOLD = 'BANKACCOUNTS.UPDATED.STATUS.COMPLIANCEHOLD',
  BANKACCOUNTSUPDATEDSTATUSDELETED = 'BANKACCOUNTS.UPDATED.STATUS.DELETED',
  PAPERCHECKSCREATED = 'PAPERCHECKS.CREATED',
  PAPERCHECKSUPDATEDDETAILSMODIFIED = 'PAPERCHECKS.UPDATED.DETAILS.MODIFIED',
  PAPERCHECKSUPDATEDSTATUSCANCELLED = 'PAPERCHECKS.UPDATED.STATUS.CANCELLED',
  PAPERCHECKSUPDATEDSTATUSINPROGRESS = 'PAPERCHECKS.UPDATED.STATUS.INPROGRESS',
  PAPERCHECKSUPDATEDSTATUSREDEEMED = 'PAPERCHECKS.UPDATED.STATUS.REDEEMED',
  PAYMENTQUOTESACCEPTED = 'PAYMENTQUOTES.ACCEPTED',
  PAYMENTQUOTESCANCELLED = 'PAYMENTQUOTES.CANCELLED',
  PAYMENTQUOTESCREATED = 'PAYMENTQUOTES.CREATED',
  PAYMENTQUOTESVOIDED = 'PAYMENTQUOTES.VOIDED',
  PREPAIDCARDSCREATED = 'PREPAIDCARDS.CREATED',
  PREPAIDCARDSUPDATEDSTATUSACTIVE = 'PREPAIDCARDS.UPDATED.STATUS.ACTIVE',
  PREPAIDCARDSUPDATEDSTATUSCLOSED = 'PREPAIDCARDS.UPDATED.STATUS.CLOSED',
  PREPAIDCARDSUPDATEDSTATUSCLOSEDEXPIRED = 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDEXPIRED',
  PREPAIDCARDSUPDATEDSTATUSCLOSEDFRAUD = 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDFRAUD',
  PREPAIDCARDSUPDATEDSTATUSCLOSEDLOST = 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDLOST',
  PREPAIDCARDSUPDATEDSTATUSCLOSEDSTOLEN = 'PREPAIDCARDS.UPDATED.STATUS.CLOSEDSTOLEN',
  PREPAIDCARDSUPDATEDSTATUSCOMPLIANCEHOLD = 'PREPAIDCARDS.UPDATED.STATUS.COMPLIANCEHOLD',
  PREPAIDCARDSUPDATEDSTATUSPENDINGACTIVATION = 'PREPAIDCARDS.UPDATED.STATUS.PENDINGACTIVATION',
  PREPAIDCARDSUPDATEDSTATUSPENDINGORDER = 'PREPAIDCARDS.UPDATED.STATUS.PENDINGORDER',
  PREPAIDCARDSUPDATEDSTATUSPENDINGRELEASE = 'PREPAIDCARDS.UPDATED.STATUS.PENDINGRELEASE',
  PREPAIDCARDSUPDATEDSTATUSSUSPENDED = 'PREPAIDCARDS.UPDATED.STATUS.SUSPENDED',
  RECEIPTSCREATED = 'RECEIPTS.CREATED',
  RECEIPTSUPDATEDDETAILSMODIFIED = 'RECEIPTS.UPDATED.DETAILS.MODIFIED',
  RECEIPTSUPDATEDSTATUSCANCELLED = 'RECEIPTS.UPDATED.STATUS.CANCELLED',
  RECEIPTSUPDATEDSTATUSCOMPLETED = 'RECEIPTS.UPDATED.STATUS.COMPLETED',
  RECEIPTSUPDATEDSTATUSEXPIRED = 'RECEIPTS.UPDATED.STATUS.EXPIRED',
  RECEIPTSUPDATEDSTATUSFAILED = 'RECEIPTS.UPDATED.STATUS.FAILED',
  RECEIPTSUPDATEDSTATUSPENDING = 'RECEIPTS.UPDATED.STATUS.PENDING',
  RECEIPTSUPDATEDSTATUSPROCESSING = 'RECEIPTS.UPDATED.STATUS.PROCESSING',
  RECEIPTSUPDATEDSTATUSREFUNDED = 'RECEIPTS.UPDATED.STATUS.REFUNDED',
  RECEIPTSUPDATEDSTATUSRETURNED = 'RECEIPTS.UPDATED.STATUS.RETURNED',
  RECEIPTSUPDATEDSTATUSREVERSED = 'RECEIPTS.UPDATED.STATUS.REVERSED',
  RECEIPTSUPDATEDSTATUSREVIEWREQUIRED = 'RECEIPTS.UPDATED.STATUS.REVIEWREQUIRED',
  RECEIPTSUPDATEDSTATUSSCHEDULED = 'RECEIPTS.UPDATED.STATUS.SCHEDULED',
  SPENDBACKQUOTESACCEPTED = 'SPENDBACKQUOTES.ACCEPTED',
  SPENDBACKQUOTESCANCELLED = 'SPENDBACKQUOTES.CANCELLED',
  SPENDBACKQUOTESCREATED = 'SPENDBACKQUOTES.CREATED',
  SPENDBACKQUOTESVOIDED = 'SPENDBACKQUOTES.VOIDED',
  TRANSFERQUOTESACCEPTED = 'TRANSFERQUOTES.ACCEPTED',
  TRANSFERQUOTESCANCELLED = 'TRANSFERQUOTES.CANCELLED',
  TRANSFERQUOTESCREATED = 'TRANSFERQUOTES.CREATED',
  TRANSFERQUOTESVOIDED = 'TRANSFERQUOTES.VOIDED',
  USEREVENTSCOMPLETED = 'USEREVENTS.COMPLETED',
  USEREVENTSSTARTED = 'USEREVENTS.STARTED',
  USEREVENTSUPDATED = 'USEREVENTS.UPDATED',
  USERSCREATED = 'USERS.CREATED',
  USERSUPDATEDIDVFAILED = 'USERS.UPDATED.IDV.FAILED',
  USERSUPDATEDIDVPASSED = 'USERS.UPDATED.IDV.PASSED',
  USERSUPDATEDKYCAPPROVED = 'USERS.UPDATED.KYC.APPROVED',
  USERSUPDATEDKYCPROVIDED = 'USERS.UPDATED.KYC.PROVIDED',
  USERSUPDATEDKYCREJECTED = 'USERS.UPDATED.KYC.REJECTED',
  USERSUPDATEDKYCREQUIRED = 'USERS.UPDATED.KYC.REQUIRED',
  USERSUPDATEDSTATUSREGISTRATIONCOMPLETE = 'USERS.UPDATED.STATUS.REGISTRATIONCOMPLETE',
  USERSUPDATEDSTATUSREGISTRATIONINPROGRESS = 'USERS.UPDATED.STATUS.REGISTRATIONINPROGRESS',
  UNKNOWN = 'UNKNOWN',
}

/**
 * Schema for WebhookNamespaces
 */
export const webhookNamespacesSchema: Schema<WebhookNamespaces> = stringEnum(WebhookNamespaces);
